import { reactive } from 'vue'

const state = reactive({
  lang: 'en',
})

const translations = {
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_services: 'Services',
    nav_gallery: 'Gallery',
    nav_photos: 'Photos',
    nav_videos: 'Videos',
    nav_destination: 'Destination',
    nav_contacts: 'Contacts',
    translator: 'Language',
    select_language: 'Select language',
    kinyarwanda: 'Kinyarwanda',
    english: 'English',
    french: 'French',
    spanish: 'Spanish',
    chinese: 'Chinese',
    portuguese: 'Portuguese',
    photos_title: 'Photo Gallery',
    photos_intro: 'A bright collection of Rwanda photos that capture nature, culture, and adventure.',
    photo_caption_1: 'Morning mist over Lake Kivu',
    photo_caption_2: 'Sunrise at Akagera National Park',
    photo_caption_3: 'Nyungwe rain forest canopy walkway',
    photo_caption_4: 'Rwanda hills and village views',
    photo_caption_5: 'Traditional art and local market',
    videos_title: 'Video Gallery',
    videos_intro: 'Watch curated Rwanda travel highlights and natural landscapes.',
    video_caption_1: 'Safari highlights from Akagera',
    video_caption_2: 'Kigali city culture and food',
    video_caption_3: 'Lake Kivu shores and sunsets',
    northern_title: 'Northern Rwanda',
    northern_description: 'Home to volcanoes, gorillas, and misty mountain vistas.',
    northern_feature_1: 'Gorilla trekking in Volcanoes National Park',
    northern_feature_2: 'Golden monkey forest encounters',
    northern_feature_3: 'Hiking the Musanze caves and hills',
    southern_title: 'Southern Rwanda',
    southern_description: 'Lush forests, tea plantations and lakeside retreats.',
    southern_feature_1: 'Nyungwe canopy walk and chimp tracking',
    southern_feature_2: 'Tea plantation tours and birdwatching',
    southern_feature_3: 'Cultural villages and local markets',
    eastern_title: 'Eastern Rwanda',
    eastern_description: 'Wide savannahs and wildlife-rich national parks.',
    eastern_feature_1: 'Akagera safari drives and boat tours',
    eastern_feature_2: 'Lake Ihema birding and boat safaris',
    eastern_feature_3: 'Cultural heritage and scenic farms',
    western_title: 'Western Rwanda',
    western_description: 'Lake Kivu adventures, waterfalls, and forest hikes.',
    western_feature_1: 'Lake Kivu boat trips and island tours',
    western_feature_2: 'Nyungwe rainforest canopy and waterfalls',
    western_feature_3: 'Hiking and hot springs near Cyangugu',
    kigali_title: 'Kigali City',
    kigali_description: 'A modern capital with museums, markets, and vibrant dining.',
    kigali_feature_1: 'Visit the Kigali Genocide Memorial',
    kigali_feature_2: 'Explore local markets and art galleries',
    kigali_feature_3: 'Enjoy Kigali nightlife and cuisine',
  },
  rw: {
    nav_home: 'Ahabanza',
    nav_about: 'Ibyerekeye',
    nav_services: 'Serivisi',
    nav_gallery: 'Ibyerekanwa',
    nav_photos: 'Amafoto',
    nav_videos: 'Amashusho',
    nav_destination: 'Aho ujya',
    nav_contacts: 'Twandikire',
    translator: 'Ururimi',
    select_language: 'Hitamo ururimi',
    kinyarwanda: 'Ikinyarwanda',
    english: 'Icyongereza',
    french: 'Igifaransa',
    spanish: 'Icyesipanyolo',
    chinese: 'Igishinwa',
    portuguese: 'Igiporutigali',
    photos_title: 'Icyumba cy’amafoto',
    photos_intro: 'Amafoto meza y’u Rwanda yerekana kamere, umuco, n’ubutwari.',
    photo_caption_1: 'Umutaka mu gitondo aho Lake Kivu iherereye',
    photo_caption_2: 'Izuba rirashe muri Pariki ya Akagera',
    photo_caption_3: 'Umuhanda wo mu ishyamba rya Nyungwe',
    photo_caption_4: 'Imisozi n’umudugudu by’u Rwanda',
    photo_caption_5: 'Ubuhanzi gakondo n’isoko rya hano',
    videos_title: 'Icyumba cy’amashusho',
    videos_intro: 'Reba amashusho yihariye y’abagenzi ba Rwanda n’imiterere y’igihugu.',
    video_caption_1: 'Ibyiza bya safari muri Akagera',
    video_caption_2: 'Umujyi wa Kigali n’umuco',
    video_caption_3: 'Umucanga wa Lake Kivu n’izuba riva',
    northern_title: 'Amajyaruguru y’u Rwanda',
    northern_description: 'Aho hari imisozi, ingagi, n’ahantu hameze nk’umuyaga.',
    northern_feature_1: 'Gukora ingendo z’inguzi mu Pariki y’ibyiza bya Volcanoes',
    northern_feature_2: 'Kubona ingagi n’impongo z’umuhondo',
    northern_feature_3: 'Kuzamuka mu musozi no gusura inkangu za Musanze',
    southern_title: 'Amajyepfo y’u Rwanda',
    southern_description: 'Ishyamba ry’icyatsi, tea, n’imitaka y’ibiyaga.',
    southern_feature_1: 'Gutembera ku kiraro cya Nyungwe no kureba ingagi',
    southern_feature_2: 'Gusura tea n’inyoni',
    southern_feature_3: 'Amahanga y’umuco n’isoko ryaho',
    eastern_title: 'Iburasirazuba bw’u Rwanda',
    eastern_description: 'Imirima nini n’ibihugu by’umwimerere.',
    eastern_feature_1: 'Safari muri Akagera n’icyambu',
    eastern_feature_2: 'Kureba inyoni kuri Lake Ihema',
    eastern_feature_3: 'Gusura umuco n’imirima myiza',
    western_title: 'Ibiyaga by’Uburengerazuba',
    western_description: 'Lake Kivu, amatembere, n’ishyamba.',
    western_feature_1: 'Ingendo ku kiyaga cya Kivu n’imiziyombo',
    western_feature_2: 'Ishyamba rya Nyungwe n’amazi y’uruvange',
    western_feature_3: 'Kuzamuka no kureba amashyamba ya Cyangugu',
    kigali_title: 'Umujyi wa Kigali',
    kigali_description: 'Umurwa mukuru w’umurongo n’amamyuza, amasoko, n’amafunguro asusurutsa.',
    kigali_feature_1: 'Gusura aho urupfu rwa Jenoside rwerekanirizwa',
    kigali_feature_2: 'Gusura amasoko n’amazu y’ubugeni',
    kigali_feature_3: 'Kuryoherwa n’ubuzima bw’umujyi na cuisine',
  },
  fr: {
    nav_home: 'Accueil',
    nav_about: 'À propos',
    nav_services: 'Services',
    nav_gallery: 'Galerie',
    nav_photos: 'Photos',
    nav_videos: 'Vidéos',
    nav_destination: 'Destination',
    nav_contacts: 'Contacts',
    translator: 'Langue',
    select_language: 'Choisir la langue',
    kinyarwanda: 'Kinyarwanda',
    english: 'Anglais',
    french: 'Français',
    spanish: 'Espagnol',
    chinese: 'Chinois',
    portuguese: 'Portugais',
    photos_title: 'Galerie de photos',
    photos_intro: 'Une belle collection de photos du Rwanda capturant nature, culture et aventure.',
    photo_caption_1: 'Brume matinale sur le lac Kivu',
    photo_caption_2: 'Lever de soleil au parc national d’Akagera',
    photo_caption_3: 'Passerelle dans la forêt de Nyungwe',
    photo_caption_4: 'Collines du Rwanda et vues de villages',
    photo_caption_5: 'Art traditionnel et marché local',
    videos_title: 'Galerie vidéo',
    videos_intro: 'Regardez des vidéos sélectionnées du Rwanda.',
    video_caption_1: 'Moments de safari à Akagera',
    video_caption_2: 'Culture et cuisine de Kigali',
    video_caption_3: 'Rives et couchers de soleil du lac Kivu',
    northern_title: 'Nord du Rwanda',
    northern_description: 'Volcans, gorilles et vues de montagne brumeuses.',
    northern_feature_1: 'Trekking de gorilles au parc national des volcans',
    northern_feature_2: 'Rencontres avec les singes dorés',
    northern_feature_3: 'Randonnée dans les grottes et collines de Musanze',
    southern_title: 'Sud du Rwanda',
    southern_description: 'Forêts luxuriantes, plantations de thé et retraites au bord des lacs.',
    southern_feature_1: 'Passerelle de la canopée de Nyungwe et suivi des chimpanzés',
    southern_feature_2: 'Visites de plantations de thé et ornithologie',
    southern_feature_3: 'Villages culturels et marchés locaux',
    eastern_title: 'Est du Rwanda',
    eastern_description: 'Vastes savanes et parcs nationaux riches en faune.',
    eastern_feature_1: 'Safaris et excursions en bateau à Akagera',
    eastern_feature_2: 'Observation des oiseaux à Lake Ihema',
    eastern_feature_3: 'Patrimoine culturel et fermes panoramiques',
    western_title: 'Ouest du Rwanda',
    western_description: 'Aventures au lac Kivu, cascades et randonnées en forêt.',
    western_feature_1: 'Excursions en bateau sur le lac Kivu',
    western_feature_2: 'Forêt de Nyungwe et cascades',
    western_feature_3: 'Randonnées et sources chaudes près de Cyangugu',
    kigali_title: 'Ville de Kigali',
    kigali_description: 'Capitale moderne avec musées, marchés et vie nocturne animée.',
    kigali_feature_1: 'Visiter le Mémorial du génocide de Kigali',
    kigali_feature_2: 'Explorer les marchés et galeries d’art',
    kigali_feature_3: 'Profiter de la vie nocturne et de la cuisine',
  },
  es: {
    nav_home: 'Inicio',
    nav_about: 'Acerca de',
    nav_services: 'Servicios',
    nav_gallery: 'Galería',
    nav_photos: 'Fotos',
    nav_videos: 'Videos',
    nav_destination: 'Destino',
    nav_contacts: 'Contactos',
    translator: 'Idioma',
    select_language: 'Seleccionar idioma',
    kinyarwanda: 'Kinyarwanda',
    english: 'Inglés',
    french: 'Francés',
    spanish: 'Español',
    chinese: 'Chino',
    portuguese: 'Portugués',
    photos_title: 'Galería de fotos',
    photos_intro: 'Una hermosa colección de fotos de Ruanda que capturan naturaleza, cultura y aventura.',
    photo_caption_1: 'Niebla de la mañana sobre el lago Kivu',
    photo_caption_2: 'Amanecer en el parque Akagera',
    photo_caption_3: 'Pasarela en el bosque Nyungwe',
    photo_caption_4: 'Colinas de Ruanda y vistas de aldeas',
    photo_caption_5: 'Arte tradicional y mercado local',
    videos_title: 'Galería de videos',
    videos_intro: 'Mira videos seleccionados de Ruanda.',
    video_caption_1: 'Momentos de safari en Akagera',
    video_caption_2: 'Cultura y comida de Kigali',
    video_caption_3: 'Orillas y puestas de sol del lago Kivu',
    northern_title: 'Norte de Ruanda',
    northern_description: 'Volcanes, gorilas y vistas de montañas brumosas.',
    northern_feature_1: 'Trekking de gorilas en el parque nacional de los volcanes',
    northern_feature_2: 'Encuentros con monos dorados',
    northern_feature_3: 'Senderismo en las cuevas y colinas de Musanze',
    southern_title: 'Sur de Ruanda',
    southern_description: 'Bosques frondosos, plantaciones de té y retiros junto al lago.',
    southern_feature_1: 'Caminata por la canopia de Nyungwe y avistamiento de chimpancés',
    southern_feature_2: 'Visitas a plantaciones de té y observación de aves',
    southern_feature_3: 'Pueblos culturales y mercados locales',
    eastern_title: 'Este de Ruanda',
    eastern_description: 'Amplias sabanas y parques nacionales ricos en vida silvestre.',
    eastern_feature_1: 'Safaris y paseos en barco en Akagera',
    eastern_feature_2: 'Observación de aves en el lago Ihema',
    eastern_feature_3: 'Patrimonio cultural y granjas panorámicas',
    western_title: 'Oeste de Ruanda',
    western_description: 'Aventuras en el lago Kivu, cascadas y excursiones por el bosque.',
    western_feature_1: 'Paseos en barco por el lago Kivu',
    western_feature_2: 'Bosque Nyungwe y cascadas',
    western_feature_3: 'Senderismo y aguas termales cerca de Cyangugu',
    kigali_title: 'Ciudad de Kigali',
    kigali_description: 'Una capital moderna con museos, mercados y vida nocturna vibrante.',
    kigali_feature_1: 'Visitar el Memorial del Genocidio de Kigali',
    kigali_feature_2: 'Explorar mercados y galerías de arte',
    kigali_feature_3: 'Disfrutar de la vida nocturna y la cocina',
  },
  pt: {
    nav_home: 'Início',
    nav_about: 'Sobre',
    nav_services: 'Serviços',
    nav_gallery: 'Galeria',
    nav_photos: 'Fotos',
    nav_videos: 'Vídeos',
    nav_destination: 'Destino',
    nav_contacts: 'Contatos',
    translator: 'Idioma',
    select_language: 'Selecionar idioma',
    kinyarwanda: 'Kinyarwanda',
    english: 'Inglês',
    french: 'Francês',
    spanish: 'Espanhol',
    chinese: 'Chinês',
    portuguese: 'Português',
    photos_title: 'Galeria de fotos',
    photos_intro: 'Uma bela coleção de fotos de Ruanda que capturam natureza, cultura e aventura.',
    photo_caption_1: 'Névoa da manhã sobre o Lago Kivu',
    photo_caption_2: 'Nascer do sol no Parque Akagera',
    photo_caption_3: 'Passarela na floresta Nyungwe',
    photo_caption_4: 'Colinas de Ruanda e vistas de aldeias',
    photo_caption_5: 'Arte tradicional e mercado local',
    videos_title: 'Galeria de vídeos',
    videos_intro: 'Assista a vídeos selecionados de Ruanda.',
    video_caption_1: 'Destaques do safári em Akagera',
    video_caption_2: 'Cultura e comida de Kigali',
    video_caption_3: 'Margens e pores do sol do Lago Kivu',
    northern_title: 'Norte de Ruanda',
    northern_description: 'Vulcões, gorilas e vistas de montanhas enevoadas.',
    northern_feature_1: 'Trekking de gorilas no Parque Nacional dos Vulcões',
    northern_feature_2: 'Encontros com macacos dourados',
    northern_feature_3: 'Caminhadas nas cavernas e colinas de Musanze',
    southern_title: 'Sul de Ruanda',
    southern_description: 'Florestas exuberantes, plantações de chá e retiros à beira do lago.',
    southern_feature_1: 'Caminho de copa da Nyungwe e observação de chimpanzés',
    southern_feature_2: 'Passeios em plantações de chá e observação de aves',
    southern_feature_3: 'Vilarejos culturais e mercados locais',
    eastern_title: 'Leste de Ruanda',
    eastern_description: 'Amplas savanas e parques nacionais ricos em vida selvagem.',
    eastern_feature_1: 'Safáris e passeios de barco em Akagera',
    eastern_feature_2: 'Observação de aves no Lago Ihema',
    eastern_feature_3: 'Patrimônio cultural e fazendas panorâmicas',
    western_title: 'Oeste de Ruanda',
    western_description: 'Aventuras no Lago Kivu, cachoeiras e trilhas na floresta.',
    western_feature_1: 'Passeios de barco no Lago Kivu',
    western_feature_2: 'Floresta Nyungwe e cachoeiras',
    western_feature_3: 'Caminhadas e fontes termais perto de Cyangugu',
    kigali_title: 'Cidade de Kigali',
    kigali_description: 'Uma capital moderna com museus, mercados e vida noturna vibrante.',
    kigali_feature_1: 'Visitar o Memorial do Genocídio de Kigali',
    kigali_feature_2: 'Explorar mercados e galerias de arte',
    kigali_feature_3: 'Aproveitar a vida noturna e a culinária',
  },
}

const languages = [
  { code: 'rw', labelKey: 'kinyarwanda' },
  { code: 'en', labelKey: 'english' },
  { code: 'fr', labelKey: 'french' },
  { code: 'es', labelKey: 'spanish' },
  { code: 'zh', labelKey: 'chinese' },
  { code: 'pt', labelKey: 'portuguese' },
]

export function useTranslator() {
  const setLanguage = (code) => {
    if (translations[code]) {
      state.lang = code
    }
  }

  const t = (key) => {
    const locale = translations[state.lang] || translations.en
    return locale[key] || key
  }

  return {
    state,
    t,
    setLanguage,
    languages,
  }
}
